### ISSUE TITLE
Question about the name docbuilder

### ISSUE THREAD

**Issue by HerveMignot** [shakna-israel/docbuilder#90]
_I am using an issue since the email address for this package on pypi.org is broken._

Dear James,

we would like to propose an open source Python package called docbuilder.
I found you were already using this name on Pypi, but for a package that has not been updated for years.

Would you mind if we take over the “docbuilder” name?
This would be use for a registered trademark or any commercial activity, just open source contribution.

Best regards,

Hervé

**Comment by shakna-israel** [comment]
I'm afraid I still use docbuilder, as it is.
The project's not dead, I just haven't prioritised changing some underlying architectual things to it.

**Comment by HerveMignot** [comment]
Ok, thank you, we'll find something else!
BR
